name    'conduct/openidm'
version '0.0.1'
author 'Eivind Mikkelsen <eivindm@conduct.no>'
license 'Simplified BSD License'
summary 'Configuration of OpenIDM'
description 'Module for configuration of ForgeRock OpenIDM'
project_page 'https://github.com/ConductAS/puppet-openidm'
